name: Conges CI

on:
  push:
    branches: [ "${{ github.event.repository.default_branch }}" ]  
    
env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore ./src/WebApplicationConges.sln
      
    - name: Build
      run: dotnet build ./src/WebApplicationConges.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ./src/WebApplicationConges.sln --no-restore --verbosity normal
      
    - uses: actions/checkout@v3
    - name: Build the Docker image      
      run: docker build ./src/ --file ./src/Dockerfile --tag my-image-name:$(date +%s)
